server:
  port: 8515
spring:
  application:
    name: service-pay

#    引入支付宝配置文件
  config:
    import: application-alipay.yml


  cloud:
    nacos:
      discovery:
        server-addr: 192.168.231.110:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.231.110:3307/db_spzx?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=true
    username: root
    password: 123456
  data:
    redis:
      host: 192.168.231.110
      port: 6379
      password: 123456
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations:  classpath*:/mapper/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: is_deleted
      logic-delete-value: 0
      logic-not-delete-value: 1








