server:
  port: 8514

spring:
  application:
    name: service-order
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.231.110:8848
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.231.110:3307/db_spzx?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=true
    username: root
    password: 123456
  data:
    redis:
      host: 192.168.231.110
      port: 6379
      password: 123456



mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-value:  1
      logic-not-delete-value: 0
      logic-delete-field: is_deleted
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
